name: CI

on: [push, pull_request]

jobs:
  ci:
    name: ${{ matrix.os }} for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-msvc
          - x86_64-apple-darwin
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: target/release/silicon-api
            release_name: linux-x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: target/release/silicon-api.exe
            release_name: windows-x86_64.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: target/release/silicon-api
            release_name: macos-x86_64

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install libx11-xcb-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: ${{ !github.head_ref }}
        with:
          name: ${{ matrix.release_name }}
          path: ${{ matrix.artifact_name }}
